import TanstackProvider from "@/providers/TanstackProvider";
import Header from "@/common/components/Header";
import { Poppins } from "next/font/google";
import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./globals.css";
import { AuthProvider } from "@/auth/context/AuthContext";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "TaskPlatform",
  // TODO: poner la descripción del proyecto
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <TanstackProvider>
          <AuthProvider>
            <Header />
            <main>{children}</main>
            <Toaster position="top-right" richColors />
          </AuthProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
